### ISSUE TITLE
Build failure during quick start instructions

### ISSUE THREAD

**Issue by bjaress** [dmjio/miso#521] opened 2019-08-14 14:50 UTC
**Describe the bug**
Build failure during quick start instructions

**To Reproduce**
1. Follow the quick start instructions
2. Include the optional steps
3. On "nix-build" step

**Expected behavior**
Sample app built

**Actual Error**
```
building '/nix/store/hqnbn969w76sh9r02p384hrl7369r695-all-cabal-hashes-component-happy-1.19.9.drv'...
all-cabal-hashes-00d16ba60110e6956b6f7d31d520d0a34377b047/happy/1.19.9/happy.cabal
all-cabal-hashes-00d16ba60110e6956b6f7d31d520d0a34377b047/happy/1.19.9/happy.json
mv: cannot move 'all-cabal-hashes-00d16ba60110e6956b6f7d31d520d0a34377b047/happy/1.19.9/happy.json' to '/nix/store/qmqammgx7j6q5ji9c9g95hvw4388fikj-all-cabal-hashes-component-happy-1.19.9/happy.json': No such file or directory
mv: cannot move 'all-cabal-hashes-00d16ba60110e6956b6f7d31d520d0a34377b047/happy/1.19.9/happy.cabal' to '/nix/store/qmqammgx7j6q5ji9c9g95hvw4388fikj-all-cabal-hashes-component-happy-1.19.9/happy.cabal': No such file or directory
builder for '/nix/store/hqnbn969w76sh9r02p384hrl7369r695-all-cabal-hashes-component-happy-1.19.9.drv' failed with exit code 1
cannot build derivation '/nix/store/76zva1k7sdwr7x06sq7hm71wjhnrl4wx-cabal2nix-happy-1.19.9.drv': 1 dependencies couldn't be built
error: build of '/nix/store/76zva1k7sdwr7x06sq7hm71wjhnrl4wx-cabal2nix-happy-1.19.9.drv' failed
(use '--show-trace' to show detailed location information)
```

Adding `--show-trace` gives:

```
building '/nix/store/hqnbn969w76sh9r02p384hrl7369r695-all-cabal-hashes-component-happy-1.19.9.drv'...
all-cabal-hashes-00d16ba60110e6956b6f7d31d520d0a34377b047/happy/1.19.9/happy.cabal
all-cabal-hashes-00d16ba60110e6956b6f7d31d520d0a34377b047/happy/1.19.9/happy.json
mv: cannot move 'all-cabal-hashes-00d16ba60110e6956b6f7d31d520d0a34377b047/happy/1.19.9/happy.json' to '/nix/store/qmqammgx7j6q5ji9c9g95hvw4388fikj-all-cabal-hashes-component-happy-1.19.9/happy.json': No such file or directory
mv: cannot move 'all-cabal-hashes-00d16ba60110e6956b6f7d31d520d0a34377b047/happy/1.19.9/happy.cabal' to '/nix/store/qmqammgx7j6q5ji9c9g95hvw4388fikj-all-cabal-hashes-component-happy-1.19.9/happy.cabal': No such file or directory
builder for '/nix/store/hqnbn969w76sh9r02p384hrl7369r695-all-cabal-hashes-component-happy-1.19.9.drv' failed with exit code 1
cannot build derivation '/nix/store/76zva1k7sdwr7x06sq7hm71wjhnrl4wx-cabal2nix-happy-1.19.9.drv': 1 dependencies couldn't be built
error: while evaluating the attribute 'buildInputs' of the derivation 'app-0.1.0.0' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/generic-builder.nix:245:3:
while evaluating the attribute 'buildInputs' of the derivation 'miso-1.0.0.0' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/generic-builder.nix:245:3:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'jsaddle-warp-0.9.5.0' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/generic-builder.nix:245:3:
while evaluating the attribute 'buildPhase' of the derivation 'ghcjs-8.6.0.1' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/compilers/ghcjs-ng/default.nix:67:5:
while evaluating the attribute 'buildInputs' of the derivation 'ghcjs-8.6.0.1' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/generic-builder.nix:245:3:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'ghc-api-ghcjs-8.6.2' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/generic-builder.nix:245:3:
while evaluating the attribute 'nativeBuildInputs' of the derivation 'alex-3.2.4' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/generic-builder.nix:245:3:
while evaluating 'getOutput' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/lib/attrsets.nix:464:23, called from undefined position:
while evaluating anonymous function at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/stdenv/generic/make-derivation.nix:134:17, called from undefined position:
while evaluating 'dontCheck' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/lib.nix:104:15, called from /nix/store/dic3xnm2jajsnkb072dv2pswg3ffy6sv-source/default.nix:31:21:
while evaluating 'overrideCabal' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/lib.nix:37:24, called from /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/lib.nix:104:20:
while evaluating 'callPackageKeepDeriver' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/make-package-set.nix:157:33, called from /nix/store/dic3xnm2jajsnkb072dv2pswg3ffy6sv-source/default.nix:31:32:
while evaluating 'overrideCabal' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/lib.nix:37:24, called from /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/make-package-set.nix:158:5:
while evaluating 'callPackage' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/make-package-set.nix:114:22, called from /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/make-package-set.nix:158:20:
while evaluating 'callPackageWithScope' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/make-package-set.nix:74:37, called from /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/make-package-set.nix:114:28:
while evaluating 'makeOverridable' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/lib/customisation.nix:67:24, called from /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/make-package-set.nix:97:8:
while evaluating 'drvScope' at /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/pkgs/development/haskell-modules/make-package-set.nix:87:18, called from /nix/store/9r1vhvri4ba913g4vyg5jqrhg6pb9amn-source/lib/customisation.nix:69:12:
build of '/nix/store/76zva1k7sdwr7x06sq7hm71wjhnrl4wx-cabal2nix-happy-1.19.9.drv' failed
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: None used
 - Version: OS version 18.10

**Comment by dmjio** [comment] 2019-08-14 15:18
I can't reproduce on version 1.0 and 1.1. Can you paste the exact commands that you ran?

**Comment by bjaress** [comment] 2019-08-14 15:26
```

**Comment by dmjio** [comment] 2019-08-14 15:29
@bjaress can you paste all of the build output in a gist.

**Comment by bjaress** [comment] 2019-08-14 15:32
Sure.  I'll have to remove everything and start over to get all the output (nix wants to pick up where it left off) but I can do that tonight.  Thank you for looking into it.

**Comment by dmjio** [comment] 2019-08-14 15:44
Ok cool, thanks for looking into this. Can you paste which version of nix you have as well. `nix —version`

**Comment by bjaress** [comment] 2019-08-15 04:17
I think reinstalling nix helped.  At least, it's doing a lot more now.  It might not finish until tomorrow, but it looks promising.

**Comment by dmjio** [comment] 2019-08-15 05:05
@bjaress it shouldn’t take longer than a few minutes if the cache is working properly to copy all of the binaries locally. Sometimes the cache does down though. Do you see a lot of, “Copying from ... haskell-miso.cachix.org” ?

**Comment by bjaress** [comment] 2019-08-15 11:07
I did see some of that at the beginning, but then it spend a few hours compiling things I was a little surprised it needed to compile, like gcc, libc, and Perl.   I don't really know much about nix, so I figured it knew what it needed, but then it eventually failed.

I started over again, this time reinstalling nix *and* deleting /nix, and if failed much sooner with:

```
unpacking 'https://github.com/dmjio/miso/archive/4e15d92cc4f37605fc398229695de4d903ef8a47.tar.gz'...
error: hash mismatch in file downloaded from 'https://github.com/dmjio/miso/archive/4e15d92cc4f37605fc398229695de4d903ef8a47.tar.gz':
  wanted: sha256:1lwr35p9074b7wgz0jh4f2pjc7ls8isgzmn9xl86vb6cvsm035kf
  got:    sha256:0kg9lg18qdsnb6gw3jmnl49widzf5cy151bls7k09d5dxlm0myd8
```

**Comment by bjaress** [comment] 2019-08-15 12:03
https://gist.github.com/bjaress/bf0f76e5f836eec2d508f0dfda1158bd

**Comment by manveru** [comment] 2019-08-16 12:23
Just hit the same issue. You can easily fix that yourself by replacing the hash in the `sample-app/default.nix` file. It's mysterious though why the hash of that tarball would change.

**Comment by dmjio** [comment] 2019-08-16 13:59
Should be fixed in https://github.com/dmjio/miso/commit/adea0fa4a1d66f6a688538cc79d915c612fd38ad

I had specified the hash to an older version of miso which was not related to the revision. Nix doesn't compare the revision to the hash, just simply trusts the hash is what I wanted, fetched from my local cache, and used that version of miso. For users who do not have miso cached locally at that hash, the revision would have been fetched, the `sha256` calculated, and found incorrect (what @bjaress experienced).

The sample app should be cached too now, so now building should have to occur.
```
pushing /nix/store/yfamhk3bsa336bigp9409ba8akjh15a3-app-0.1.0.0
All done.
```

**Closed by dmjio** 2019-08-16 13:59 UTC

**Comment by bjaress** [comment] 2019-08-16 14:54
Thank you!
