### ISSUE TITLE
stack install gets stuck

### ISSUE THREAD

**Issue by pamu** [dmjio/miso#450] opened 2018-08-17 16:23 UTC
# stack install gets stuck

```
2018-08-17 19:20:07.084960: [debug] Encoding /private/var/folders/j2/ht70vy4j7w9c8m5hzvd43sq80000gp/T/stack76718/profunctors-5.2/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0_ghcjs/stack-config-cache
@(src/Stack/Build/Cache.hs:164:7)
2018-08-17 19:20:07.092864: [debug] Finished writing /private/var/folders/j2/ht70vy4j7w9c8m5hzvd43sq80000gp/T/stack76718/profunctors-5.2/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0_ghcjs/stack-config-cache
@(src/Stack/Build/Cache.hs:164:7)
2018-08-17 19:20:07.093167: [debug] Encoding /private/var/folders/j2/ht70vy4j7w9c8m5hzvd43sq80000gp/T/stack76718/profunctors-5.2/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0_ghcjs/stack-cabal-mod
@(src/Stack/Build/Cache.hs:173:7)
2018-08-17 19:20:07.093736: [debug] Finished writing /private/var/folders/j2/ht70vy4j7w9c8m5hzvd43sq80000gp/T/stack76718/profunctors-5.2/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0_ghcjs/stack-cabal-mod
@(src/Stack/Build/Cache.hs:173:7)
2018-08-17 19:20:07.094089: [info] profunctors-5.2: build
@(src/Stack/Build/Execute.hs:873:23)
2018-08-17 19:20:07.094436: [debug] Run process within /private/var/folders/j2/ht70vy4j7w9c8m5hzvd43sq80000gp/T/stack76718/profunctors-5.2/: /Users/foobar/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_1.24.0.0_ghcjs-0.2.0.9006030_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0_ghcjs build --ghcjs-options " -ddump-hi -ddump-to-file"
@(src/Stack/Build/Execute.hs:1133:29)
Progress 0/7
```

**Comment by madnight** [comment] 2018-08-17 17:33
Have you tried nix?

**Comment by pamu** [comment] 2018-08-17 20:35
@madnight I would like to, Could you please suggest any tutorials for getting started with nix?

**Comment by madnight** [comment] 2018-08-17 20:50
Sure, which Operating System do you use? By the way, you can also join #haskell on freenode https://webchat.freenode.net and ask any question there, the community is exceptionally friendly.

**Comment by pamu** [comment] 2018-08-18 21:57
@madnight I use mac os lastest

**Comment by madnight** [comment] 2018-08-18 22:14
You might try https://www.corajr.com/posts/2014/12/22/nix-osx-haskell/
And then follow https://github.com/dmjio/miso#nix

**Comment by Maxxen** [comment] 2019-01-20 21:43
I was just about to write a reply to this thread when I switched workspace and saw that it magically resolved itself. I think the problem is just that the cabal build step takes an insane amount of time with no progress indicator. The crazy CPU usage spike is not really reassuring either, but I digress.

>Im having the exact same issue. I might also add that ghc CPU usage shoots up to 100%, much like >#3830 and #3572. `rm -rf ~/.stack/indices/ ` did not fix my issue however, it seems like the cabal build >process gets stuck after processing indices.

**Comment by dmjio** [comment] 2019-01-20 21:45
closing for now, re-open if persists, but do note stack has officially deprecated support for nix.

**Closed by dmjio** 2019-01-20 21:45 UTC
