### ISSUE TITLE
Initial benchmark results

### ISSUE THREAD

**Issue by saurabhnanda** [dmjio/miso#225] opened 2017-08-01 15:14 UTC
Just raised a PR to get Miso included in the JS framework benchmark at https://github.com/krausest/js-framework-benchmark/pull/223

Here are the results from running the benchmark for three frameworks (Miso, Elm, & Vanilla JS) on my local machine: 

![js-benchmarks](https://user-images.githubusercontent.com/28369/28832365-dabab808-76f9-11e7-9b12-80175f4f98c8.png)

Here's the benchmarking code for Miso - https://github.com/vacationlabs/js-framework-benchmark/blob/master/miso-ghcjs-keyed/app/Main.hs Let me know if I'm doing something particularly stupid from a benchmarking standpoint.

**Comment by saurabhnanda** [comment] 2017-08-01 15:23
Btw, apart from struggling with the editor integration (which I gave up on, btw), writing this benchmark in Miso was extremely straightforward and simple!

**Comment by cocreature** [comment] 2017-08-01 16:27
Benchmarks are always nice!

Here are a few things that might be worth experimenting with
* Use `MisoString` (which is just `JSString` when compiled using `ghcjs`) instead of `String`.
* `adjectives`, `colours` and `nouns` should be vectors since you are accessing them by index.

**Comment by saurabhnanda** [comment] 2017-08-01 16:43
@cocreature I'm wondering if Vectors are helping or hurting the benchmark. Looked the the [Elm code](https://github.com/vacationlabs/js-framework-benchmark/blob/54e326bf9326e68843c3efb5f70ed14b41e26a45/elm-v0.18.0-keyed/src/Main.elm#L320-L324) which is using a regular `List` and performing so much better.

It's just three benchmarks where the elements in the middle of Vector need to be changed are where Miso is significantly slower than Elm. For the others, the performance is actually pretty respectable!

**Comment by cocreature** [comment] 2017-08-01 16:48
@saurabhnanda I think we are talking about two different things here. `adjectives`, `colours` and `nouns` are never changed so I really can’t imagine `Vector` causing problems for these (assuming GHCjs is behaving somewhat reasonable here). `modelRows` which *is* a vector in your benchmark is actually changed so there lists or some other data structure (I haven’t looked too closely what is done to this field) might actually be benefitial.

**Comment by dmjio** [comment] 2017-08-01 16:50
@saurabhnanda, thanks for the "FYI". Will try and take a look at what you did. One thing to note, you have `miso-ghcjs-keyed`, but the `keys` patch isn't finished yet. https://github.com/dmjio/miso/issues/113.

I'm adjusting your github issue title to something less provocative.

**Comment by dmjio** [comment] 2017-08-01 16:58
@saurabhnanda, thanks for doing this. I'd take try to update things to use `JSString`, instead of `String`, which is known to be inefficient. Check out the `pack` function in `Miso.String`. Also, instead of using `System.Random`, I'd make an ffi call to `Math.random()`.

```haskell
foreign import javascript unsafe "$r = Math.random()" 
  getRandom :: IO Double
```

**Comment by dmjio** [comment] 2017-08-01 17:06
@saurabhnanda it would be nice to have a way to run these benchmarks from the `miso` build itself.  We should consider adding what you did to this repo, and the nix build scripts. So when releases /  PRs are made, we can check for regressions.

**Comment by saurabhnanda** [comment] 2017-08-01 17:12
I have a feeling the issue lies elsewhere. Take a look at the benchmarks that are slow:

* Update the **text** of every 10th row in the table after it has been constructed. This just appends `!!!` to the text. The construction of a 10,000 row table is only 1.4x slower than Elm (this is where 30,000 calls are made to the random function, btw). That has far more string operations that updating every 10th row.
* Selecting a row: changes the `modelHighlightedRowIndex` field in the Model which controls whether the `danger` class is applied to one particular row in the entire table. How can this be 5x slower than Elm? Specifically when Elm's underlying model is using a List to represent the rows. Is Vector slowing us down here or is the vdom-diffing slowing us down?
* Similar case for swapping rows.

**Comment by saurabhnanda** [comment] 2017-08-01 17:13
> @saurabhnanda it would be nice to have a way to run these benchmarks from the miso build itself. We should consider adding what you did to this repo, and the nix build scripts. So when releases / PRs are made, we can check for regressions.

Let me know what to do. I'll raise a PR.

**Comment by dmjio** [comment] 2017-08-01 17:42
> Update the text of every 10th row in the table after it has been constructed. This just appends !!! to the text. 

There might be ways in the diffing algorithm we can optimize for this, right now it doesn't attempt to perform string matching, it just checks if the strings are different and replaces. It would be a lot of tweaking for little gain. Let's see if the issue is elsewhere.

> The construction of a 10,000 row table is only 1.4x slower than Elm (this is where 30,000 calls are made to the random function, btw). 

Not bad, can you humor me and use the `FFI` call to `Math.random()` instead? Also, can you try to use plain `Vector` (i.e. don't update the vector in IO), just to see the difference. I think the issue is with `randomRIO`.

> Similar case for swapping rows.

Once the keys patch is in (referenced above), this will be competitive.

**Comment by dmjio** [comment] 2017-08-01 17:44
And as @cocreature said, use `MisoString` instead of `String`

**Comment by dmjio** [comment] 2017-08-01 19:33
`Math.random` for row creation speed, `MisoString` for startup speed and row manipulation.

**Comment by dmjio** [comment] 2017-08-01 20:27
@saurabhnanda for future reference, it might be best to coordinate changes like this with me, i.e. adding benchmarks for `miso` to other repos. Not trying to dissuade you from contributing, and I'm glad that we have benchmarks now (however correct), I'm trying to establish a protocol for communication / and workflow centered around [CONTRIBUTING.md](https://github.com/dmjio/miso/blob/master/CONTRIBUTING.md) and [CODE_OF_CONDUCT.md](https://github.com/dmjio/miso/blob/master/CODE_OF_CONDUCT.md)

So I recommend you join the miso slack, and we can discuss further.

**Comment by dmjio** [comment] 2017-08-01 22:47
Related https://github.com/dmjio/miso/issues/26

**Comment by saurabhnanda** [comment] 2017-08-02 02:18
Tried using Vector for adjectives, odours, and nouns and it doesn't make a dent. Going to try MisoString next. 

I still have a feeling that it's the underlying data structure that is the problem here.

**Comment by saurabhnanda** [comment] 2017-08-02 04:27
Result of using MisoString: https://github.com/vacationlabs/js-framework-benchmark/commit/95f2987d1641c7ccff3a698f16931c67b0742a3b

```
Create 1,000 rows - Miso 1.9x slower than Elm
Replace 1,000 rows - Miso 1.4x FASTER than Elm
Update every 10th row - Miso 3.7x slower than Elm
Select row - Miso 4.8x slower than Elm
Swap row - Miso 2.9x slower than Elm
Remove row - Miso 1.9x slower than Elm
Create 10,000 rows - Miso 1.5x slower than Elm
Append rows - Miso 2.8x slower than Elm
Clear 10,000 rows - Miso at-par with Elm
Startup time - Miso 2.6x slower than Elm
```

I'm still confused about how to use MisoString. Discussion at #224

**Comment by dmjio** [comment] 2017-08-02 04:28
@saurabhnanda nice, I might have a fix for `MisoString` on `prop_` and `style_`, stay tuned.

**Comment by dmjio** [comment] 2017-08-02 04:28
> Replace 1,000 rows - Miso 1.4x FASTER than Elm

That's a start

**Comment by saurabhnanda** [comment] 2017-08-02 04:41
The following patch makes the row generation **slightly faster** than using `System.Random`

![screenshot 2017-08-02 10 12 41](https://user-images.githubusercontent.com/28369/28857937-913fbef0-776a-11e7-8812-d264c6b713b1.png)

```
Create 1,000 rows - Miso 1.6x slower than Elm (as opposed to 1.9x slower)
Create 10,000 rows - Miso 1.3x slower than Elm (as opposed to 1.5x slower)
Append rows - Miso 2.7x slower than Elm (as opposed to 2.8x slower)
```

Based on the little impact this has, I would not recommend resorting to this technique just for the purpose of the benchmark.

**Comment by dmjio** [comment] 2017-08-02 04:50
Nice work. Can you try using just plain vectors (if possible), not mutable ones? Doing the record updates by way of actions will fork a thread, it's a little bit of indirection.

**Comment by dmjio** [comment] 2017-08-02 06:10
Also, add some bang patterns to the field in the model.

**Comment by saurabhnanda** [comment] 2017-08-02 06:21
> Can you try using just plain vectors (if possible), not mutable ones?

Where are mutable vectors being used? Apart from the swapping-rows case? (I'm sorry, first time that I'm using vectors).

**Comment by saurabhnanda** [comment] 2017-08-02 06:28
Made things worse by about 1.5x across the board -- https://github.com/vacationlabs/js-framework-benchmark/commit/b2b15668333a29e815df77aa5c1166b8aca68be0

Reverting that commits.

**Comment by saurabhnanda** [comment] 2017-08-02 08:23
[Using a non-IO random generator](https://github.com/vacationlabs/js-framework-benchmark/commit/dd08f0b429c286ff09a7348cad94d5442910b9e9)

```
Create 1,000 rows - Miso 1.9x slower than Elm (as opposed to 1.9x slower)
Create 10,000 rows - Miso 1.6x slower than Elm (as opposed to 1.5x slower)
Append rows - Miso 2.8x slower than Elm (as opposed to 2.8x slower)
```

Random number generation doesn't seem to be the problem here. Reverting this commit and closing this particular thread of investigation.

**Comment by saurabhnanda** [comment] 2017-08-02 08:25
> There might be ways in the diffing algorithm we can optimize for this, right now it doesn't attempt to perform string matching, it just checks if the strings are different and replaces. It would be a lot of tweaking for little gain. Let's see if the issue is elsewhere.

@dmjio any other ideas? I'm actually amazed at how fast Elm it even though it's using a `List` for the core model. Probably the slowdown is not because of the model representation but either the vdom-diffing or GHCJS. Thoughts?

**Comment by dmjio** [comment] 2017-08-02 16:21
@saurabhnanda did you try adding bang patterns? Otherwise, no worries. I'll try to take a look at what you did soon.

**Comment by saurabhnanda** [comment] 2017-08-03 03:51
>  did you try adding bang patterns? 

Nope, didn't try that. How is that expected to help? The largest thing is the Vector, which I'm assuming is already strict, and not lazy, right?

**Comment by dmjio** [comment] 2017-08-03 04:01
I recommend reading up on `BangPatterns`, https://ocharles.org.uk/blog/posts/2014-12-05-bang-patterns.html. If you look at the mario example, it uses them. The vector you're using is strict. But performing updates like this in `IO` a little strange.

**Comment by saurabhnanda** [comment] 2017-08-03 05:52
> But performing updates like this in IO is a little strange.

Even if one uses the FFI version of `Math.random` that'd end up being the case, right? Is there a way around it? Also, what is the intended use-case for allowing the `update` function to have effects (if this is not the intended use)?

**Comment by dmjio** [comment] 2017-08-03 06:33
Closing due to lack of willingess to collaborate with other members.

> Being respectful of differing viewpoints and experiences

> Focusing on what is best for the community

> Showing empathy towards other community members

@saurabhnanda there are great resources on Haskell performance, I recommend checking the wiki. You've given us a good start, but it's clear you have different motivations that are not in line with the objectives of this project.

> Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

**Closed by dmjio** 2017-08-03 06:33 UTC
